SET SQL_SAFE_UPDATES = 0;

UPDATE article
SET DESIGNATION = UPPER(DESIGNATION)
WHERE PRIX > 10;

UPDATE article
SET DESIGNATION = LOWER(DESIGNATION)
WHERE ID = 2;

UPDATE article
SET PRIX = PRIX * 1.10
WHERE ID_FOU =(SELECT ID FROM fournisseur WHERE nom = 'FDM SA');